spring:
  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    #url: jdbc:h2:mem:maindb
    url: jdbc:postgresql://localhost:5433/stage
    username: postgres
    password: secret
    #driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      #data-locations: data.sql
      #schema-locations: schema_del.sql
  jmx:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: true

    show-sql: true
  data:
    rest:
      basePath: /datarest

#настройки actuator
management:
  endpoints:
    web:
      #base-path: /actuator
      exposure:
        include: "*"


    enabled-by-default: true
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true

logging:
  #logback:
  #  rollingpolicy:
  #    file-name-pattern: "app-%d{yyyy-MM-dd}.log."
  #file:
  #  name: logs/application-debug.log
    #path: logs
  pattern:
    console: "%d %-5level %logger : %msg%n"
  #  file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: ERROR
    ru.otus.hw.controller: "debug"
    org.springframework.web: "debug"