spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      #data-locations: data.sql
      #schema-locations: schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false

    show-sql: false


logging:
  level:
    ROOT: ERROR
    ru.otus.hw.controller: DEBUG