spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      #data-locations: data.sql
      #schema-locations: schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false

    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true

#настройки actuator
management:
  endpoints:
    web:
      #base-path: /actuator
      exposure:
        include: "*"


    enabled-by-default: true
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    diskspace:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      legacy:
        enabled: true
      enabled: true

logging:
  level:
    ROOT: ERROR
    ru.otus.hw.controller: DEBUG